# Generated by Django 4.2.7 on 2025-04-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_profile_picture_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="core.vehicle",
            ),
        ),
    ]
