# Generated by Django 4.2.7 on 2025-04-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_servicerequest_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
