# Generated by Django 4.2.7 on 2025-09-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='issue_file',
            field=models.FileField(blank=True, null=True, upload_to='issue_files/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='issue_video',
            field=models.FileField(blank=True, null=True, upload_to='issue_videos/'),
        ),
    ]
