# Generated by Django 4.2.7 on 2025-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mechanic_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SERVICE_REQUEST', 'Service Request'), ('STATUS_UPDATE', 'Status Update'), ('PAYMENT', 'Payment'), ('REVIEW', 'Review'), ('EMERGENCY', 'Emergency')], max_length=20),
        ),
    ]
