# Generated by Django 4.2.7 on 2025-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mechanic_base_fee_servicerequest_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
