# Generated by Django 4.2.7 on 2025-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mechanic_preferred_language_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Calculated distance between user and mechanic in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='problem_complexity_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee based on problem description complexity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SERVICE_REQUEST', 'Service Request'), ('STATUS_UPDATE', 'Status Update'), ('PAYMENT', 'Payment'), ('REVIEW', 'Review')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EmergencyRequest',
        ),
    ]
