# Generated by Django 4.2.7 on 2025-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servicerequest_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='mechanic_id_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic_id_proofs/'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='mechanic_id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='mechanic_id_proof_type',
            field=models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('DL', "Driver's License"), ('ID_CARD', 'Other ID Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('DL', "Driver's License"), ('ID_CARD', 'Other ID Card')], max_length=20, null=True),
        ),
    ]
